### ISSUE TITLE
Tickets number on nav show as open rather than on-hold

### ISSUE THREAD

**Issue by M-Curtis** [NickTheITGuy/OSTicket-OnHold#1]
I followed the instructions on this repo to setup on-hold and got it to work eventually however when I put a ticket on-hold the counter next to on-hold shows as 0 but the counter on open tickets shows as 1. The ticket appears under on-hold tickets but not under open.
What can I do to fix this issue.
![chrome_2017-05-03_13-51-28](https://cloud.githubusercontent.com/assets/9915817/25661228/ad30b696-3007-11e7-98e2-9b4debcbefdd.png)
![chrome_2017-05-03_13-51-50](https://cloud.githubusercontent.com/assets/9915817/25661227/ad2e4122-3007-11e7-8263-5c99fa7a5fda.png)

**Comment by M-Curtis** [comment]
<s>I've just noticed also that the icon next to the ticket does not have the same icon that is on the onhold nav. I'm sorry for any confusion these are my first experiences with osTickets.</s>
Nevermind this icon merely represents how the ticket was provided.

**Comment by M-Curtis** [comment]
Is it something to do with the ticket class loop at line 2944, would a new count have to be implemented to the array instead for this functionality?

**Comment by acid847** [comment]
I am also having the same issue with this mod has there been any update regarding this?

**Comment by NickTheITGuy** [comment]
Issue has been patched in Version 1.1

Delayed reaction, sorry for that.

Best regards,
Nick
