### ISSUE TITLE
On hold not appearing on tickets page

### ISSUE THREAD

**Issue by EBS-DarkD** [NickTheITGuy/OSTicket-OnHold#2]
I've followed the instructions to install and configure and restarted apache but I'm not seeing the 'Onhold' link/counter in the tickets menu bar

![image](https://user-images.githubusercontent.com/16149089/30275061-a78e0884-9708-11e7-943b-fc75bb5c778d.png)

If I edit the ?status= in the url, I do get to see the onhold tickets

![image](https://user-images.githubusercontent.com/16149089/30275105-de227484-9708-11e7-9b3f-26e8c9bd7154.png)

Can you give me a clue how to get this working correctly?
I'm using osTicket v1.10

**Comment by EBS-DarkD** [comment]
Also it doesn't seem to be pausing the SLA counter. Is this correct?

**Comment by NickTheITGuy** [comment]
Hi EBS,

The SLA Counter is not paused sadly, i'm planning on implementing this in the future.
Also i made a temporary workaround (the updated tickets.php file should fix the issue for now.)

Best regards,
Nick
